/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NgoAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.NgoAdminOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EducationEventWorkRequest;
import Business.WorkQueue.ManagerApprovalWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.HrRole.PlanningEventHrJPanel;

/**
 *
 * @author Anish Gupta
 */
public class educationEventJPanel extends javax.swing.JPanel {

    /**
     * Creates new form educationEventJPanel
     */
    
    JPanel userProcessContainer;
    UserAccount account;
    NgoAdminOrganization organization;
    Enterprise enterprise;
    EcoSystem business;
    
    public educationEventJPanel(JPanel userProcessContainer, UserAccount account, NgoAdminOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.business = business;
        this.enterprise = enterprise;
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)eventJTable.getModel();
        
        model.setRowCount(0);
        
                        for(WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
                                if(request instanceof EducationEventWorkRequest){
                                EducationEventWorkRequest req = (EducationEventWorkRequest) request;
                                Object[] row = new Object[1];
                    //            row[0] = request;
                    //            row[1] = request.getSender().getEmployee().getName();
                    //            row[2] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
                    //            row[3] = request.getStatus();
                                row[0] = req;

                                model.addRow(row);
                                }
                            }                            
                        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        eventJTable = new javax.swing.JTable();
        viewEducationalEventDetailsJButton = new javax.swing.JButton();
        removeEducationalEventDetailsJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backJButton3 = new javax.swing.JButton();
        createEducationalWorkshopJButton = new javax.swing.JButton();
        checkRegistrationStatusJButton = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setBackground(new java.awt.Color(255, 255, 255));

        eventJTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        eventJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Educational Workshop"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(eventJTable);

        viewEducationalEventDetailsJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewEducationalEventDetailsJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Resources/view details.png"))); // NOI18N
        viewEducationalEventDetailsJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        viewEducationalEventDetailsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEducationalEventDetailsJButtonActionPerformed(evt);
            }
        });

        removeEducationalEventDetailsJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        removeEducationalEventDetailsJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Resources/cancel event.png"))); // NOI18N
        removeEducationalEventDetailsJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        removeEducationalEventDetailsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEducationalEventDetailsJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Education Event Management");

        backJButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backJButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Resources/back.png"))); // NOI18N
        backJButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backJButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton3ActionPerformed(evt);
            }
        });

        createEducationalWorkshopJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        createEducationalWorkshopJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Resources/create educational workshop.png"))); // NOI18N
        createEducationalWorkshopJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        createEducationalWorkshopJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEducationalWorkshopJButtonActionPerformed(evt);
            }
        });

        checkRegistrationStatusJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkRegistrationStatusJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Resources/check event registration status.png"))); // NOI18N
        checkRegistrationStatusJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        checkRegistrationStatusJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRegistrationStatusJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(backJButton3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(removeEducationalEventDetailsJButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(viewEducationalEventDetailsJButton))
                                .addComponent(checkRegistrationStatusJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createEducationalWorkshopJButton)))
                    .addComponent(jLabel1))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(createEducationalWorkshopJButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeEducationalEventDetailsJButton)
                    .addComponent(viewEducationalEventDetailsJButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkRegistrationStatusJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backJButton3))
                .addContainerGap(90, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewEducationalEventDetailsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEducationalEventDetailsJButtonActionPerformed

        int selectedRow = eventJTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Select row from table");
            return;
        }

        EducationEventWorkRequest request = (EducationEventWorkRequest)eventJTable.getValueAt(selectedRow, 0);
        EducationEventDetailsJPanel viewEventDetailsJPanel = new EducationEventDetailsJPanel(userProcessContainer, request, account, enterprise, business);
        userProcessContainer.add("viewEventDetailsJPanel", viewEventDetailsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

        // TODO add your handling code here:
    }//GEN-LAST:event_viewEducationalEventDetailsJButtonActionPerformed

    private void removeEducationalEventDetailsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEducationalEventDetailsJButtonActionPerformed
        int selectedRow = eventJTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Select row from table");
            return;
        }
        EducationEventWorkRequest request = (EducationEventWorkRequest)eventJTable.getValueAt(selectedRow, 0);

        Organization org = null;
        //Enterprise enterprise =
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof NgoAdminOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().remove(request);
            account.getWorkQueue().getWorkRequestList().remove(request);
            for(Network network : business.getNetworkList()){
                for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                    for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                        for(WorkRequest req : organization.getWorkQueue().getWorkRequestList()){
                            if(req instanceof ManagerApprovalWorkRequest){
                                ManagerApprovalWorkRequest managerReq = (ManagerApprovalWorkRequest) req;
                                if(managerReq.getNgoEventReq() == request){
                                    managerReq.setStatus("Event Cancelled");
                                }
                            }
                        }
                    }
                }
            }
            //            System.out.println(org.getWorkQueue().getWorkRequestList());
        }
        JOptionPane.showMessageDialog(null, "Education Workshop Event Cancelled. Corporates notified!");
        populateTable();
    }//GEN-LAST:event_removeEducationalEventDetailsJButtonActionPerformed

    private void backJButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton3ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

                // TODO add your handling code here:
    }//GEN-LAST:event_backJButton3ActionPerformed

    private void createEducationalWorkshopJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEducationalWorkshopJButtonActionPerformed
        CreateEducationWorkshopJPanel createEducationWorkshopJPanel = new CreateEducationWorkshopJPanel(userProcessContainer, account, enterprise);
        userProcessContainer.add("createEducationWorkshopJPanel", createEducationWorkshopJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_createEducationalWorkshopJButtonActionPerformed

    private void checkRegistrationStatusJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRegistrationStatusJButtonActionPerformed
        int selectedRow = eventJTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Select row from table");
            return;
        }

        EducationEventWorkRequest request = (EducationEventWorkRequest)eventJTable.getValueAt(selectedRow, 0);
        viewEmployeesRegisteredJPanel registeredEmployeesJPanel = new viewEmployeesRegisteredJPanel(userProcessContainer, request, account, enterprise);
        userProcessContainer.add("registeredEmployeesJPanel", registeredEmployeesJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_checkRegistrationStatusJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton3;
    private javax.swing.JButton checkRegistrationStatusJButton;
    private javax.swing.JButton createEducationalWorkshopJButton;
    private javax.swing.JTable eventJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton removeEducationalEventDetailsJButton;
    private javax.swing.JButton viewEducationalEventDetailsJButton;
    // End of variables declaration//GEN-END:variables
}
