/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NgoAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.NgoAdminOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EducationEventWorkRequest;
import Business.WorkQueue.HealthEventWorkRequest;
import Business.WorkQueue.ManagerApprovalWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.HospitalAdminRole.PlanningHealthCheckupCampJPanel;
import userinterface.HrRole.PlanningEventHrJPanel;

/**
 *
 * @author Anish Gupta
 */
public class NgoAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NgoAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    NgoAdminOrganization organization;
    Enterprise enterprise;
    EcoSystem business;
    
    public NgoAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, NgoAdminOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
    }
    
              
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        viewQuizPerformanceJButton = new javax.swing.JButton();
        eduEventJButton = new javax.swing.JButton();
        healthEventJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("NGO Event Management Portal");

        viewQuizPerformanceJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewQuizPerformanceJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Resources/view children quiz scores.png"))); // NOI18N
        viewQuizPerformanceJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        viewQuizPerformanceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewQuizPerformanceJButtonActionPerformed(evt);
            }
        });

        eduEventJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        eduEventJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Resources/ed event workshop.png"))); // NOI18N
        eduEventJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        eduEventJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eduEventJButtonActionPerformed(evt);
            }
        });

        healthEventJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        healthEventJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Resources/create health checkup camp.png"))); // NOI18N
        healthEventJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        healthEventJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                healthEventJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewQuizPerformanceJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(healthEventJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eduEventJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addComponent(eduEventJButton)
                .addGap(33, 33, 33)
                .addComponent(healthEventJButton)
                .addGap(40, 40, 40)
                .addComponent(viewQuizPerformanceJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewQuizPerformanceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewQuizPerformanceJButtonActionPerformed
        ViewQuizScoresJPanel viewQuizScoresJPanel = new ViewQuizScoresJPanel(userProcessContainer, account, organization, enterprise, business);
        userProcessContainer.add("viewQuizScoresJPanel", viewQuizScoresJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);    
        // TODO add your handling code here:
    }//GEN-LAST:event_viewQuizPerformanceJButtonActionPerformed

    private void healthEventJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_healthEventJButtonActionPerformed
        HealthEventJPanel healthEventJPanel = new HealthEventJPanel(userProcessContainer, account, organization, enterprise, business);
        userProcessContainer.add("healthEventJPanel", healthEventJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_healthEventJButtonActionPerformed

    private void eduEventJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eduEventJButtonActionPerformed
//        EducationEventWorkRequest request = (EducationEventWorkRequest)eventJTable.getValueAt(selectedRow, 0);
        educationEventJPanel educationWorkshopEventJPanel = new educationEventJPanel(userProcessContainer, account, organization, enterprise, business);
        userProcessContainer.add("educationWorkshopEventJPanel", educationWorkshopEventJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_eduEventJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eduEventJButton;
    private javax.swing.JButton healthEventJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton viewQuizPerformanceJButton;
    // End of variables declaration//GEN-END:variables
}
