/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ChildRole;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.EducationEventWorkRequest;
import UserInterface.Rewards.YouTubeViewer1;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Anish Gupta
 */
public class ChildQuizJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChildQuizJPanel
     */
    
    JPanel userProcessContainer;
    EducationEventWorkRequest request;
    UserAccount account;
    private YouTubeViewer1 youtubeViewer;
    
    public ChildQuizJPanel(JPanel userProcessContainer, EducationEventWorkRequest request, UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.account = account;
        q1JTextField.setText(request.getQuiz().getQuestions().get(0).getQuestion());
        a1aTextField.setText(request.getQuiz().getQuestions().get(0).getAnswerA());
        a1bTextField.setText(request.getQuiz().getQuestions().get(0).getAnswerB());
        a1cTextField.setText(request.getQuiz().getQuestions().get(0).getAnswerC());
        a1dTextField.setText(request.getQuiz().getQuestions().get(0).getAnswerD());
        q2JTextField.setText(request.getQuiz().getQuestions().get(1).getQuestion());
        a2aTextField.setText(request.getQuiz().getQuestions().get(1).getAnswerA());
        a2bTextField.setText(request.getQuiz().getQuestions().get(1).getAnswerB());
        a2cTextField.setText(request.getQuiz().getQuestions().get(1).getAnswerC());
        a2dTextField.setText(request.getQuiz().getQuestions().get(1).getAnswerD());
        q3JTextField.setText(request.getQuiz().getQuestions().get(2).getQuestion());
        a3aTextField.setText(request.getQuiz().getQuestions().get(2).getAnswerA());
        a3bTextField.setText(request.getQuiz().getQuestions().get(2).getAnswerB());
        a3cTextField.setText(request.getQuiz().getQuestions().get(2).getAnswerC());
        a3dTextField.setText(request.getQuiz().getQuestions().get(2).getAnswerD());
        q4JTextField.setText(request.getQuiz().getQuestions().get(3).getQuestion());
        a4aTextField.setText(request.getQuiz().getQuestions().get(3).getAnswerA());
        a4bTextField.setText(request.getQuiz().getQuestions().get(3).getAnswerB());
        a4cTextField.setText(request.getQuiz().getQuestions().get(3).getAnswerC());
        a4dTextField.setText(request.getQuiz().getQuestions().get(3).getAnswerD());
        q5JTextField.setText(request.getQuiz().getQuestions().get(4).getQuestion());
        a5aTextField.setText(request.getQuiz().getQuestions().get(4).getAnswerA());
        a5bTextField.setText(request.getQuiz().getQuestions().get(4).getAnswerB());
        a5cTextField.setText(request.getQuiz().getQuestions().get(4).getAnswerC());
        a5dTextField.setText(request.getQuiz().getQuestions().get(4).getAnswerD());
    }
    
    private void disableRadio() {
        q1AJRadioButton.setEnabled(false);
        q1BJRadioButton.setEnabled(false);
        q1CJRadioButton.setEnabled(false);
        q1DJRadioButton.setEnabled(false);
        
        q2AJRadioButton.setEnabled(false);
        q2BJRadioButton.setEnabled(false);
        q2CJRadioButton.setEnabled(false);
        q2DJRadioButton.setEnabled(false);
        
        q3AJRadioButton.setEnabled(false);
        q3BJRadioButton.setEnabled(false);
        q3CJRadioButton.setEnabled(false);
        q3DJRadioButton.setEnabled(false);
        
        q4AJRadioButton.setEnabled(false);
        q4BJRadioButton.setEnabled(false);
        q4CJRadioButton.setEnabled(false);
        q4DJRadioButton.setEnabled(false);
        
        q5AJRadioButton.setEnabled(false);
        q5BJRadioButton.setEnabled(false);
        q5CJRadioButton.setEnabled(false);
        q5DJRadioButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        q2JTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        q2AJRadioButton = new javax.swing.JRadioButton();
        q2BJRadioButton = new javax.swing.JRadioButton();
        q2CJRadioButton = new javax.swing.JRadioButton();
        q3DJRadioButton = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        q3JTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        q3AJRadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        submitQuizJButton = new javax.swing.JButton();
        q5DJRadioButton = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        q5JTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        q1JTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        q1AJRadioButton = new javax.swing.JRadioButton();
        q1BJRadioButton = new javax.swing.JRadioButton();
        q1CJRadioButton = new javax.swing.JRadioButton();
        q1DJRadioButton = new javax.swing.JRadioButton();
        q5AJRadioButton = new javax.swing.JRadioButton();
        q2DJRadioButton = new javax.swing.JRadioButton();
        q5BJRadioButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        q3BJRadioButton = new javax.swing.JRadioButton();
        q5CJRadioButton = new javax.swing.JRadioButton();
        q3CJRadioButton = new javax.swing.JRadioButton();
        q4DJRadioButton = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        q4JTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        q4AJRadioButton = new javax.swing.JRadioButton();
        q4BJRadioButton = new javax.swing.JRadioButton();
        q4CJRadioButton = new javax.swing.JRadioButton();
        a1aTextField = new javax.swing.JTextField();
        a1bTextField = new javax.swing.JTextField();
        a1dTextField = new javax.swing.JTextField();
        a1cTextField = new javax.swing.JTextField();
        a2aTextField = new javax.swing.JTextField();
        a2bTextField = new javax.swing.JTextField();
        a2dTextField = new javax.swing.JTextField();
        a2cTextField = new javax.swing.JTextField();
        a3aTextField = new javax.swing.JTextField();
        a3bTextField = new javax.swing.JTextField();
        a3cTextField = new javax.swing.JTextField();
        a3dTextField = new javax.swing.JTextField();
        a4aTextField = new javax.swing.JTextField();
        a4bTextField = new javax.swing.JTextField();
        a4cTextField = new javax.swing.JTextField();
        a4dTextField = new javax.swing.JTextField();
        a5cTextField = new javax.swing.JTextField();
        a5dTextField = new javax.swing.JTextField();
        a5bTextField = new javax.swing.JTextField();
        a5aTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        q2JTextField.setEditable(false);
        q2JTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Answer :");

        q2AJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q2AJRadioButton.setText("A");
        q2AJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2AJRadioButtonActionPerformed(evt);
            }
        });

        q2BJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q2BJRadioButton.setText("B");
        q2BJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2BJRadioButtonActionPerformed(evt);
            }
        });

        q2CJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q2CJRadioButton.setText("C");
        q2CJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2CJRadioButtonActionPerformed(evt);
            }
        });

        q3DJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q3DJRadioButton.setText("D");
        q3DJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3DJRadioButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Q3.");

        q3JTextField.setEditable(false);
        q3JTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Answer :");

        q3AJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q3AJRadioButton.setText("A");
        q3AJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3AJRadioButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Fun Quiz");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Q1.");

        submitQuizJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submitQuizJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Resources/submit quiz.png"))); // NOI18N
        submitQuizJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        submitQuizJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitQuizJButtonActionPerformed(evt);
            }
        });

        q5DJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q5DJRadioButton.setText("D");
        q5DJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5DJRadioButtonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Q5.");

        q5JTextField.setEditable(false);
        q5JTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Answer :");

        q1JTextField.setEditable(false);
        q1JTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Answer :");

        q1AJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q1AJRadioButton.setText("A");
        q1AJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1AJRadioButtonActionPerformed(evt);
            }
        });

        q1BJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q1BJRadioButton.setText("B");
        q1BJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1BJRadioButtonActionPerformed(evt);
            }
        });

        q1CJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q1CJRadioButton.setText("C");
        q1CJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1CJRadioButtonActionPerformed(evt);
            }
        });

        q1DJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q1DJRadioButton.setText("D");
        q1DJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1DJRadioButtonActionPerformed(evt);
            }
        });

        q5AJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q5AJRadioButton.setText("A");
        q5AJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5AJRadioButtonActionPerformed(evt);
            }
        });

        q2DJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q2DJRadioButton.setText("D");
        q2DJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2DJRadioButtonActionPerformed(evt);
            }
        });

        q5BJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q5BJRadioButton.setText("B");
        q5BJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5BJRadioButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Q2.");

        q3BJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q3BJRadioButton.setText("B");
        q3BJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3BJRadioButtonActionPerformed(evt);
            }
        });

        q5CJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q5CJRadioButton.setText("C");
        q5CJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5CJRadioButtonActionPerformed(evt);
            }
        });

        q3CJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q3CJRadioButton.setText("C");
        q3CJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3CJRadioButtonActionPerformed(evt);
            }
        });

        q4DJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q4DJRadioButton.setText("D");
        q4DJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4DJRadioButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Q4.");

        q4JTextField.setEditable(false);
        q4JTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Answer :");

        q4AJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q4AJRadioButton.setText("A");
        q4AJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4AJRadioButtonActionPerformed(evt);
            }
        });

        q4BJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q4BJRadioButton.setText("B");
        q4BJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4BJRadioButtonActionPerformed(evt);
            }
        });

        q4CJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q4CJRadioButton.setText("C");
        q4CJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4CJRadioButtonActionPerformed(evt);
            }
        });

        a1aTextField.setEditable(false);
        a1aTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        a1bTextField.setEditable(false);
        a1bTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        a1dTextField.setEditable(false);
        a1dTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        a1cTextField.setEditable(false);
        a1cTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        a2aTextField.setEditable(false);
        a2aTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        a2bTextField.setEditable(false);
        a2bTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        a2dTextField.setEditable(false);
        a2dTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        a2cTextField.setEditable(false);
        a2cTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        a3aTextField.setEditable(false);
        a3aTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        a3bTextField.setEditable(false);
        a3bTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        a3cTextField.setEditable(false);
        a3cTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        a3dTextField.setEditable(false);
        a3dTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        a4aTextField.setEditable(false);
        a4aTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        a4bTextField.setEditable(false);
        a4bTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        a4cTextField.setEditable(false);
        a4cTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        a4dTextField.setEditable(false);
        a4dTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        a5cTextField.setEditable(false);
        a5cTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        a5dTextField.setEditable(false);
        a5dTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        a5bTextField.setEditable(false);
        a5bTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        a5aTextField.setEditable(false);
        a5aTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        backJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Resources/back.png"))); // NOI18N
        backJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q1JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(q1BJRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(a1bTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(q1AJRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(a1aTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(q1DJRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(a1dTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(q1CJRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(a1cTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q2JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q2AJRadioButton)
                                    .addComponent(q2BJRadioButton))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(a2bTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(a2aTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q2CJRadioButton)
                                    .addComponent(q2DJRadioButton))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(a2dTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(a2cTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(q4JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(q4AJRadioButton)
                                .addComponent(q4BJRadioButton))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(a4bTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(a4aTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(q4CJRadioButton)
                                .addComponent(q4DJRadioButton))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(a4cTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(a4dTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(q3JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(q3AJRadioButton)
                                        .addComponent(q3BJRadioButton))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(a3bTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(a3aTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(30, 30, 30)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(q3CJRadioButton)
                                        .addComponent(q3DJRadioButton))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(a3cTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(a3dTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(q5AJRadioButton)
                                .addComponent(q5BJRadioButton))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(a5bTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(a5aTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(q5DJRadioButton)
                                .addComponent(q5CJRadioButton))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(a5cTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(a5dTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(submitQuizJButton)
                                .addGap(96, 96, 96))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addComponent(q5JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 111, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(q1JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(q1AJRadioButton)
                    .addComponent(q1CJRadioButton)
                    .addComponent(a1aTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a1cTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q1BJRadioButton)
                    .addComponent(q1DJRadioButton)
                    .addComponent(a1bTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a1dTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(q2JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(q2AJRadioButton))
                        .addGap(5, 5, 5)
                        .addComponent(q2BJRadioButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a2aTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a2cTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q2CJRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a2bTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a2dTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q2DJRadioButton))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(q3JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(q3AJRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(q3BJRadioButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a3aTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a3cTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q3CJRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a3bTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a3dTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q3DJRadioButton))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(q4JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a4aTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a4cTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q4CJRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(a4bTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(q4DJRadioButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(a4dTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(q4AJRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(q4BJRadioButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q5JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(q5AJRadioButton)
                            .addComponent(q5CJRadioButton))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q5BJRadioButton)
                            .addComponent(q5DJRadioButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a5aTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a5cTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(a5bTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a5dTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitQuizJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backJButton))
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void q2AJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2AJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2AJRadioButtonActionPerformed

    private void q2BJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2BJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2BJRadioButtonActionPerformed

    private void q2CJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2CJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2CJRadioButtonActionPerformed

    private void q3DJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3DJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3DJRadioButtonActionPerformed

    private void q3AJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3AJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3AJRadioButtonActionPerformed

    private void submitQuizJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitQuizJButtonActionPerformed
        
              
        Integer marks1, marks2, marks3, marks4, marks5, totalMarks, quizTotalMarks;
        
        
        String answer1 = q1AJRadioButton.isSelected() ? "A" : (q1BJRadioButton.isSelected() ? "B" : (q1CJRadioButton.isSelected() ? "C" : (q1DJRadioButton.isSelected() ? "D" : "No")));
        if(answer1.equals(request.getQuiz().getQuestions().get(0).getAnswer())){
            marks1 = request.getQuiz().getQuestions().get(0).getMarks();
            }
        else
            marks1 = 0;
        
        
        String answer2 = q2AJRadioButton.isSelected() ? "A" : (q2BJRadioButton.isSelected() ? "B" : (q2CJRadioButton.isSelected() ? "C" : (q2DJRadioButton.isSelected() ? "D" : "No")));
        if(answer2.equals(request.getQuiz().getQuestions().get(1).getAnswer())){
            marks2 = request.getQuiz().getQuestions().get(1).getMarks();
            }
        else
            marks2 = 0;
        
        
        String answer3 = q3AJRadioButton.isSelected() ? "A" : (q3BJRadioButton.isSelected() ? "B" : (q3CJRadioButton.isSelected() ? "C" : (q3DJRadioButton.isSelected() ? "D" : "No")));
        if(answer3.equals(request.getQuiz().getQuestions().get(2).getAnswer())){
            marks3 = request.getQuiz().getQuestions().get(2).getMarks();
            }
        else
            marks3 = 0;
        
        
        String answer4 = q4AJRadioButton.isSelected() ? "A" : (q4BJRadioButton.isSelected() ? "B" : (q4CJRadioButton.isSelected() ? "C" : (q4DJRadioButton.isSelected() ? "D" : "No")));
        if(answer4.equals(request.getQuiz().getQuestions().get(3).getAnswer())){
            marks4 = request.getQuiz().getQuestions().get(3).getMarks();
            }
        else
            marks4 = 0;
        
        
        String answer5 = q5AJRadioButton.isSelected() ? "A" : (q5BJRadioButton.isSelected() ? "B" : (q5CJRadioButton.isSelected() ? "C" : (q5DJRadioButton.isSelected() ? "D" : "No")));
        if(answer5.equals(request.getQuiz().getQuestions().get(4).getAnswer())){
            marks5 = request.getQuiz().getQuestions().get(4).getMarks();
            }
        else
            marks5 = 0;
        
        totalMarks = marks1 + marks2 + marks3 + marks4 + marks5;
        quizTotalMarks = request.getQuiz().getQuestions().get(0).getMarks() + request.getQuiz().getQuestions().get(1).getMarks() + request.getQuiz().getQuestions().get(2).getMarks() + request.getQuiz().getQuestions().get(3).getMarks() + request.getQuiz().getQuestions().get(4).getMarks();
        account.getEmployee().getQuizScore().add(totalMarks);
        account.getEmployee().getQuizScoreMap().put(request.getQuiz().getQuizName(), totalMarks);
//        JOptionPane.showMessageDialog(null, "Quiz Completed! Your Score is : " + (totalMarks/quizTotalMarks)*100);
        int input = JOptionPane.showOptionDialog(null, "Woohooo! Well Done!", "Enjoy !!!.", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
        if(input == JOptionPane.OK_OPTION)
        {
            this.youtubeViewer = new YouTubeViewer1();
            String[] arguments = new String[] {"Hello"};
            try
            {
                youtubeViewer.main(arguments);     
            }
            catch (java.lang.IllegalStateException e)
            {
                System.out.println("java.lang.IllegalStateException Caught."); 
            }
        }
        System.out.println("Score " + (totalMarks/quizTotalMarks)*100);
        
        disableRadio();
        
        account.getEmployee().getQuizTakenEdEventWorkReq().add(request);
        // TODO add your handling code here:
    }//GEN-LAST:event_submitQuizJButtonActionPerformed

    private void q5DJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5DJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q5DJRadioButtonActionPerformed

    private void q1AJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1AJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1AJRadioButtonActionPerformed

    private void q1BJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1BJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1BJRadioButtonActionPerformed

    private void q1CJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1CJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1CJRadioButtonActionPerformed

    private void q1DJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1DJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1DJRadioButtonActionPerformed

    private void q5AJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5AJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q5AJRadioButtonActionPerformed

    private void q2DJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2DJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2DJRadioButtonActionPerformed

    private void q5BJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5BJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q5BJRadioButtonActionPerformed

    private void q3BJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3BJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3BJRadioButtonActionPerformed

    private void q5CJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5CJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q5CJRadioButtonActionPerformed

    private void q3CJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3CJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3CJRadioButtonActionPerformed

    private void q4DJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4DJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4DJRadioButtonActionPerformed

    private void q4AJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4AJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4AJRadioButtonActionPerformed

    private void q4BJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4BJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4BJRadioButtonActionPerformed

    private void q4CJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4CJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4CJRadioButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
        Component[] comps = userProcessContainer.getComponents();
        for(Component c: comps) {
            if(c instanceof ChildWorkAreaJPanel) {
                ChildWorkAreaJPanel panel = (ChildWorkAreaJPanel) c;
                panel.populateTable();
            }
        }
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1aTextField;
    private javax.swing.JTextField a1bTextField;
    private javax.swing.JTextField a1cTextField;
    private javax.swing.JTextField a1dTextField;
    private javax.swing.JTextField a2aTextField;
    private javax.swing.JTextField a2bTextField;
    private javax.swing.JTextField a2cTextField;
    private javax.swing.JTextField a2dTextField;
    private javax.swing.JTextField a3aTextField;
    private javax.swing.JTextField a3bTextField;
    private javax.swing.JTextField a3cTextField;
    private javax.swing.JTextField a3dTextField;
    private javax.swing.JTextField a4aTextField;
    private javax.swing.JTextField a4bTextField;
    private javax.swing.JTextField a4cTextField;
    private javax.swing.JTextField a4dTextField;
    private javax.swing.JTextField a5aTextField;
    private javax.swing.JTextField a5bTextField;
    private javax.swing.JTextField a5cTextField;
    private javax.swing.JTextField a5dTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton q1AJRadioButton;
    private javax.swing.JRadioButton q1BJRadioButton;
    private javax.swing.JRadioButton q1CJRadioButton;
    private javax.swing.JRadioButton q1DJRadioButton;
    private javax.swing.JTextField q1JTextField;
    private javax.swing.JRadioButton q2AJRadioButton;
    private javax.swing.JRadioButton q2BJRadioButton;
    private javax.swing.JRadioButton q2CJRadioButton;
    private javax.swing.JRadioButton q2DJRadioButton;
    private javax.swing.JTextField q2JTextField;
    private javax.swing.JRadioButton q3AJRadioButton;
    private javax.swing.JRadioButton q3BJRadioButton;
    private javax.swing.JRadioButton q3CJRadioButton;
    private javax.swing.JRadioButton q3DJRadioButton;
    private javax.swing.JTextField q3JTextField;
    private javax.swing.JRadioButton q4AJRadioButton;
    private javax.swing.JRadioButton q4BJRadioButton;
    private javax.swing.JRadioButton q4CJRadioButton;
    private javax.swing.JRadioButton q4DJRadioButton;
    private javax.swing.JTextField q4JTextField;
    private javax.swing.JRadioButton q5AJRadioButton;
    private javax.swing.JRadioButton q5BJRadioButton;
    private javax.swing.JRadioButton q5CJRadioButton;
    private javax.swing.JRadioButton q5DJRadioButton;
    private javax.swing.JTextField q5JTextField;
    private javax.swing.JButton submitQuizJButton;
    // End of variables declaration//GEN-END:variables
}
