/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EmployeeRole;

import Business.WorkQueue.EducationEventWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Anish Gupta
 */
public class EmployeeInstructorQuizCreationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeInstructorQuizCreationJPanel
     */
    
    JPanel userProcessContainer;
    EducationEventWorkRequest request;
    
    public EmployeeInstructorQuizCreationJPanel(JPanel userProcessContainer, EducationEventWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        a4JRadioButton4 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        q1JTextField4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        a1JRadioButton4 = new javax.swing.JRadioButton();
        a2JRadioButton4 = new javax.swing.JRadioButton();
        a3JRadioButton4 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        quizNameJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        q1AJRadioButton = new javax.swing.JRadioButton();
        q1BJRadioButton = new javax.swing.JRadioButton();
        q1CJRadioButton = new javax.swing.JRadioButton();
        q1DJRadioButton = new javax.swing.JRadioButton();
        q2DJRadioButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        q2JTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        q2AJRadioButton = new javax.swing.JRadioButton();
        q2BJRadioButton = new javax.swing.JRadioButton();
        q2CJRadioButton = new javax.swing.JRadioButton();
        q3DJRadioButton = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        q3JTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        q3AJRadioButton = new javax.swing.JRadioButton();
        q3BJRadioButton = new javax.swing.JRadioButton();
        q3CJRadioButton = new javax.swing.JRadioButton();
        q4DJRadioButton = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        q4JTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        q4AJRadioButton = new javax.swing.JRadioButton();
        q4BJRadioButton = new javax.swing.JRadioButton();
        q4CJRadioButton = new javax.swing.JRadioButton();
        q5DJRadioButton = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        q5JTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        q5AJRadioButton = new javax.swing.JRadioButton();
        q5BJRadioButton = new javax.swing.JRadioButton();
        q5CJRadioButton = new javax.swing.JRadioButton();
        createQuizJButton = new javax.swing.JButton();
        ResetJButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        q1MarksJTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        q2MarksJTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        q3MarksJTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        q4MarksJTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        q5MarksJTextField = new javax.swing.JTextField();
        q1optionBJTextField = new javax.swing.JTextField();
        q1optionAJTextField = new javax.swing.JTextField();
        q1optionDJTextField = new javax.swing.JTextField();
        q1optionCJTextField = new javax.swing.JTextField();
        q2optionAJTextField = new javax.swing.JTextField();
        q2optionCJTextField = new javax.swing.JTextField();
        q2optionBJTextField = new javax.swing.JTextField();
        q2optionDJTextField = new javax.swing.JTextField();
        q3optionBJTextField = new javax.swing.JTextField();
        q3optionAJTextField = new javax.swing.JTextField();
        q3optionCJTextField = new javax.swing.JTextField();
        q3optionDJTextField = new javax.swing.JTextField();
        q4optionAJTextField = new javax.swing.JTextField();
        q4optionCJTextField = new javax.swing.JTextField();
        q4optionBJTextField = new javax.swing.JTextField();
        q4optionDJTextField = new javax.swing.JTextField();
        q5optionAJTextField = new javax.swing.JTextField();
        q5optionCJTextField = new javax.swing.JTextField();
        q5optionBJTextField = new javax.swing.JTextField();
        q5optionDJTextField = new javax.swing.JTextField();
        backJButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        q1JTextField1 = new javax.swing.JTextField();

        a4JRadioButton4.setText("D");
        a4JRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a4JRadioButton4ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Q1.");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Answer :");

        a1JRadioButton4.setText("A");
        a1JRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1JRadioButton4ActionPerformed(evt);
            }
        });

        a2JRadioButton4.setText("B");
        a2JRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2JRadioButton4ActionPerformed(evt);
            }
        });

        a3JRadioButton4.setText("C");
        a3JRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3JRadioButton4ActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Create Quiz for Children");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Q1.");

        quizNameJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Answer :");

        q1AJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q1AJRadioButton.setText("A");
        q1AJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1AJRadioButtonActionPerformed(evt);
            }
        });

        q1BJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q1BJRadioButton.setText("B");
        q1BJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1BJRadioButtonActionPerformed(evt);
            }
        });

        q1CJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q1CJRadioButton.setText("C");
        q1CJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1CJRadioButtonActionPerformed(evt);
            }
        });

        q1DJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q1DJRadioButton.setText("D");
        q1DJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1DJRadioButtonActionPerformed(evt);
            }
        });

        q2DJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q2DJRadioButton.setText("D");
        q2DJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2DJRadioButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Q2.");

        q2JTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Answer :");

        q2AJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q2AJRadioButton.setText("A");
        q2AJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2AJRadioButtonActionPerformed(evt);
            }
        });

        q2BJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q2BJRadioButton.setText("B");
        q2BJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2BJRadioButtonActionPerformed(evt);
            }
        });

        q2CJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q2CJRadioButton.setText("C");
        q2CJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2CJRadioButtonActionPerformed(evt);
            }
        });

        q3DJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q3DJRadioButton.setText("D");
        q3DJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3DJRadioButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Q3.");

        q3JTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Answer :");

        q3AJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q3AJRadioButton.setText("A");
        q3AJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3AJRadioButtonActionPerformed(evt);
            }
        });

        q3BJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q3BJRadioButton.setText("B");
        q3BJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3BJRadioButtonActionPerformed(evt);
            }
        });

        q3CJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q3CJRadioButton.setText("C");
        q3CJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3CJRadioButtonActionPerformed(evt);
            }
        });

        q4DJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q4DJRadioButton.setText("D");
        q4DJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4DJRadioButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Q4.");

        q4JTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Answer :");

        q4AJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q4AJRadioButton.setText("A");
        q4AJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4AJRadioButtonActionPerformed(evt);
            }
        });

        q4BJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q4BJRadioButton.setText("B");
        q4BJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4BJRadioButtonActionPerformed(evt);
            }
        });

        q4CJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q4CJRadioButton.setText("C");
        q4CJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4CJRadioButtonActionPerformed(evt);
            }
        });

        q5DJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q5DJRadioButton.setText("D");
        q5DJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5DJRadioButtonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Q5.");

        q5JTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Answer :");

        q5AJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q5AJRadioButton.setText("A");
        q5AJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5AJRadioButtonActionPerformed(evt);
            }
        });

        q5BJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q5BJRadioButton.setText("B");
        q5BJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5BJRadioButtonActionPerformed(evt);
            }
        });

        q5CJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q5CJRadioButton.setText("C");
        q5CJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5CJRadioButtonActionPerformed(evt);
            }
        });

        createQuizJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        createQuizJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Resources/create quiz.png"))); // NOI18N
        createQuizJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        createQuizJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createQuizJButtonActionPerformed(evt);
            }
        });

        ResetJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ResetJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Resources/reset UI.png"))); // NOI18N
        ResetJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ResetJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetJButtonActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Marks :");

        q1MarksJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Marks :");

        q2MarksJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Marks :");

        q3MarksJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Marks :");

        q4MarksJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Marks :");

        q5MarksJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        q1optionBJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        q1optionAJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        q1optionDJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        q1optionCJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        q2optionAJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        q2optionCJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        q2optionBJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        q2optionDJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        q3optionBJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        q3optionAJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        q3optionCJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        q3optionDJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        q4optionAJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        q4optionCJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        q4optionBJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        q4optionDJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        q5optionAJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        q5optionCJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        q5optionBJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        q5optionDJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        backJButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Resources/back.png"))); // NOI18N
        backJButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Quiz Name :");

        q1JTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q4BJRadioButton)
                                    .addComponent(q4AJRadioButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q4optionAJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(q4optionBJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addComponent(q4CJRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(q4optionDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(q4MarksJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(q4optionCJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel17))))
                            .addComponent(q5JTextField))
                        .addContainerGap(161, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(9, 9, 9)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(q3AJRadioButton)
                                            .addComponent(q3BJRadioButton))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(q3optionAJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(q3optionBJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(q3CJRadioButton)
                                            .addComponent(q3DJRadioButton))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(q3optionCJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel16))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(q3optionDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(q3MarksJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(q3JTextField)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(179, 179, 179)
                                        .addComponent(q4DJRadioButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(q4JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(jLabel12))
                                            .addComponent(jLabel13))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(q5BJRadioButton)
                                            .addComponent(q5AJRadioButton)))
                                    .addComponent(backJButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(createQuizJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ResetJButton))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(q5optionAJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(q5optionBJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(q5CJRadioButton)
                                            .addComponent(q5DJRadioButton))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(q5optionDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(q5optionCJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(q5MarksJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q2BJRadioButton)
                                    .addComponent(q2AJRadioButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q2optionAJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(q2optionBJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(q2CJRadioButton)
                                    .addComponent(q2DJRadioButton))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q2optionCJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(q2optionDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(q2MarksJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quizNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(q1BJRadioButton)
                                            .addComponent(q1AJRadioButton))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(q1optionAJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(q1optionBJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(q1CJRadioButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(q1DJRadioButton, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(q1optionCJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(q1optionDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(q1MarksJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(q2JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(q1JTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(quizNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q1JTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(q1AJRadioButton)
                    .addComponent(q1CJRadioButton)
                    .addComponent(jLabel14)
                    .addComponent(q1optionAJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q1optionCJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q1BJRadioButton)
                    .addComponent(q1DJRadioButton)
                    .addComponent(q1optionBJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q1optionDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q1MarksJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q2JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(q2AJRadioButton)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q2optionAJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q2optionCJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q2CJRadioButton)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q2optionBJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q2optionDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q2DJRadioButton)
                            .addComponent(q2BJRadioButton)
                            .addComponent(q2MarksJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(q3JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(q3AJRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(q3BJRadioButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(q3optionAJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(q3optionCJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(q3CJRadioButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q3optionBJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q3optionDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q3DJRadioButton)
                            .addComponent(q3MarksJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(q4JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(q4AJRadioButton)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q4DJRadioButton)
                            .addComponent(q4BJRadioButton)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q4optionAJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q4optionCJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q4CJRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q4optionBJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q4optionDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q4MarksJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(q5JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(q5AJRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q5BJRadioButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q5optionAJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q5optionCJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q5CJRadioButton)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q5optionBJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q5optionDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q5DJRadioButton)
                            .addComponent(q5MarksJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createQuizJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResetJButton)
                    .addComponent(backJButton1))
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void q1AJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1AJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1AJRadioButtonActionPerformed

    private void q1BJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1BJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1BJRadioButtonActionPerformed

    private void q1CJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1CJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1CJRadioButtonActionPerformed

    private void q1DJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1DJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1DJRadioButtonActionPerformed

    private void q2DJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2DJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2DJRadioButtonActionPerformed

    private void q2AJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2AJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2AJRadioButtonActionPerformed

    private void q2BJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2BJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2BJRadioButtonActionPerformed

    private void q2CJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2CJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2CJRadioButtonActionPerformed

    private void q3DJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3DJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3DJRadioButtonActionPerformed

    private void q3AJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3AJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3AJRadioButtonActionPerformed

    private void q3BJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3BJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3BJRadioButtonActionPerformed

    private void q3CJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3CJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3CJRadioButtonActionPerformed

    private void q4DJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4DJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4DJRadioButtonActionPerformed

    private void q4AJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4AJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4AJRadioButtonActionPerformed

    private void q4BJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4BJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4BJRadioButtonActionPerformed

    private void q4CJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4CJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4CJRadioButtonActionPerformed

    private void a4JRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a4JRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a4JRadioButton4ActionPerformed

    private void a1JRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1JRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a1JRadioButton4ActionPerformed

    private void a2JRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2JRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a2JRadioButton4ActionPerformed

    private void a3JRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3JRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a3JRadioButton4ActionPerformed

    private void q5DJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5DJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q5DJRadioButtonActionPerformed

    private void q5AJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5AJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q5AJRadioButtonActionPerformed

    private void q5BJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5BJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q5BJRadioButtonActionPerformed

    private void q5CJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5CJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q5CJRadioButtonActionPerformed

    private void ResetJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetJButtonActionPerformed
            
        
// TODO add your handling code here:
    }//GEN-LAST:event_ResetJButtonActionPerformed

    private void createQuizJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createQuizJButtonActionPerformed
        if(q1MarksJTextField.getText().equals("") || q2MarksJTextField.getText().equals("") || q3MarksJTextField.getText().equals("") || q4MarksJTextField.getText().equals("")) {
                JOptionPane.showMessageDialog(null,"One or more fields are empty");
                return;
            }
        int age;
        try{
        String question1 = quizNameJTextField.getText();
        String answer1 = q1AJRadioButton.isSelected() ? "A" : (q1BJRadioButton.isSelected() ? "B" : (q1CJRadioButton.isSelected() ? "C" : (q1DJRadioButton.isSelected() ? "D" : "No")));
        int marks1 = Integer.parseInt(q1MarksJTextField.getText());
        String answer1AText = q1optionAJTextField.getText();
        String answer1BText = q1optionBJTextField.getText();
        String answer1CText = q1optionCJTextField.getText();
        String answer1DText = q1optionDJTextField.getText();
        request.getQuiz().createQuestion(1, question1, answer1, marks1, answer1AText, answer1BText, answer1CText, answer1DText);
        String question2 = q2JTextField.getText();
        String answer2 = q2AJRadioButton.isSelected() ? "A" : (q2BJRadioButton.isSelected() ? "B" : (q2CJRadioButton.isSelected() ? "C" : (q2DJRadioButton.isSelected() ? "D" : "No")));
        int marks2 = Integer.parseInt(q2MarksJTextField.getText());
        String answer2AText = q2optionAJTextField.getText();
        String answer2BText = q2optionBJTextField.getText();
        String answer2CText = q2optionCJTextField.getText();
        String answer2DText = q2optionDJTextField.getText();
        request.getQuiz().createQuestion(2, question2, answer2, marks2, answer2AText, answer2BText, answer2CText, answer2DText);
        String question3 = q3JTextField.getText();
        String answer3 = q3AJRadioButton.isSelected() ? "A" : (q3BJRadioButton.isSelected() ? "B" : (q3CJRadioButton.isSelected() ? "C" : (q3DJRadioButton.isSelected() ? "D" : "No")));
        int marks3 = Integer.parseInt(q3MarksJTextField.getText());
        String answer3AText = q3optionAJTextField.getText();
        String answer3BText = q3optionBJTextField.getText();
        String answer3CText = q3optionCJTextField.getText();
        String answer3DText = q3optionDJTextField.getText();
        request.getQuiz().createQuestion(3, question3, answer3, marks3, answer3AText, answer3BText, answer3CText, answer3DText);
        String question4 = q4JTextField.getText();
        String answer4 = q4AJRadioButton.isSelected() ? "A" : (q4BJRadioButton.isSelected() ? "B" : (q4CJRadioButton.isSelected() ? "C" : (q4DJRadioButton.isSelected() ? "D" : "No")));
        int marks4 = Integer.parseInt(q4MarksJTextField.getText());
        String answer4AText = q4optionAJTextField.getText();
        String answer4BText = q4optionBJTextField.getText();
        String answer4CText = q4optionCJTextField.getText();
        String answer4DText = q4optionDJTextField.getText();
        request.getQuiz().createQuestion(4, question4, answer4, marks4, answer4AText, answer4BText, answer4CText, answer4DText);
        String question5 = q5JTextField.getText();
        String answer5 = q5AJRadioButton.isSelected() ? "A" : (q5BJRadioButton.isSelected() ? "B" : (q5CJRadioButton.isSelected() ? "C" : (q5DJRadioButton.isSelected() ? "D" : "No")));
        int marks5 = Integer.parseInt(q5MarksJTextField.getText());
        String answer5AText = q5optionAJTextField.getText();
        String answer5BText = q5optionBJTextField.getText();
        String answer5CText = q5optionCJTextField.getText();
        String answer5DText = q5optionDJTextField.getText();
        request.getQuiz().createQuestion(5, question5, answer5, marks5, answer5AText, answer5BText, answer5CText, answer5DText);
        request.getQuiz().setQuizName(quizNameJTextField.getText());
        JOptionPane.showMessageDialog(null, "Quiz Created!");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Enter a valid number for Marks!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_createQuizJButtonActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ResetJButton;
    private javax.swing.JRadioButton a1JRadioButton4;
    private javax.swing.JRadioButton a2JRadioButton4;
    private javax.swing.JRadioButton a3JRadioButton4;
    private javax.swing.JRadioButton a4JRadioButton4;
    private javax.swing.JButton backJButton1;
    private javax.swing.JButton createQuizJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton q1AJRadioButton;
    private javax.swing.JRadioButton q1BJRadioButton;
    private javax.swing.JRadioButton q1CJRadioButton;
    private javax.swing.JRadioButton q1DJRadioButton;
    private javax.swing.JTextField q1JTextField1;
    private javax.swing.JTextField q1JTextField4;
    private javax.swing.JTextField q1MarksJTextField;
    private javax.swing.JTextField q1optionAJTextField;
    private javax.swing.JTextField q1optionBJTextField;
    private javax.swing.JTextField q1optionCJTextField;
    private javax.swing.JTextField q1optionDJTextField;
    private javax.swing.JRadioButton q2AJRadioButton;
    private javax.swing.JRadioButton q2BJRadioButton;
    private javax.swing.JRadioButton q2CJRadioButton;
    private javax.swing.JRadioButton q2DJRadioButton;
    private javax.swing.JTextField q2JTextField;
    private javax.swing.JTextField q2MarksJTextField;
    private javax.swing.JTextField q2optionAJTextField;
    private javax.swing.JTextField q2optionBJTextField;
    private javax.swing.JTextField q2optionCJTextField;
    private javax.swing.JTextField q2optionDJTextField;
    private javax.swing.JRadioButton q3AJRadioButton;
    private javax.swing.JRadioButton q3BJRadioButton;
    private javax.swing.JRadioButton q3CJRadioButton;
    private javax.swing.JRadioButton q3DJRadioButton;
    private javax.swing.JTextField q3JTextField;
    private javax.swing.JTextField q3MarksJTextField;
    private javax.swing.JTextField q3optionAJTextField;
    private javax.swing.JTextField q3optionBJTextField;
    private javax.swing.JTextField q3optionCJTextField;
    private javax.swing.JTextField q3optionDJTextField;
    private javax.swing.JRadioButton q4AJRadioButton;
    private javax.swing.JRadioButton q4BJRadioButton;
    private javax.swing.JRadioButton q4CJRadioButton;
    private javax.swing.JRadioButton q4DJRadioButton;
    private javax.swing.JTextField q4JTextField;
    private javax.swing.JTextField q4MarksJTextField;
    private javax.swing.JTextField q4optionAJTextField;
    private javax.swing.JTextField q4optionBJTextField;
    private javax.swing.JTextField q4optionCJTextField;
    private javax.swing.JTextField q4optionDJTextField;
    private javax.swing.JRadioButton q5AJRadioButton;
    private javax.swing.JRadioButton q5BJRadioButton;
    private javax.swing.JRadioButton q5CJRadioButton;
    private javax.swing.JRadioButton q5DJRadioButton;
    private javax.swing.JTextField q5JTextField;
    private javax.swing.JTextField q5MarksJTextField;
    private javax.swing.JTextField q5optionAJTextField;
    private javax.swing.JTextField q5optionBJTextField;
    private javax.swing.JTextField q5optionCJTextField;
    private javax.swing.JTextField q5optionDJTextField;
    private javax.swing.JTextField quizNameJTextField;
    // End of variables declaration//GEN-END:variables
}
